
intervals:
  base-url: https://intervals.icu
  oauth:
    client-id: ${INTERVALS_CLIENT_ID}
    secret: ${INTERVALS_CLIENT_SECRET}

capacnan:
  buckets:
    credentials: claviger

quarkus:
  devservices:
    enabled: false
  rest-client:
    intervals:
      url: ${intervals.base-url}
      logging:
        scope: all
        body-limit: 10240
  messaging:
    nats:
      connection:
        servers:
          - "${CAPACNAN_SERVER_URI:nats://localhost:4222}"
      key-value-stores:
        claviger:
          bucket-name: ${capacnan.buckets.credentials}
          storage-type: file
          description: "Claviger: The credentials store"

'%dev':
  quarkus:
    #    compose:
    #      devservices:
    #        files:
    #          - compose-nats.yml
    log:
      #      level: DEBUG
      category:
        "io.quarkus.rest.client.reactive":
          level: DEBUG
