
intervals:
  base-url: https://intervals.icu
  oauth:
    client-id: ${INTERVALS_CLIENT_ID}
    secret: ${INTERVALS_CLIENT_SECRET}

quarkus:
  index-dependency:
    bluepring:
      group-id: it.lysz210.akasha.capacnan
      artifact-id: blueprint
  config:
    locations:
      - "${CAPACNAN_BLUEPRINT_URI:}"

  devservices:
    enabled: false
  rest-client:
    intervals:
      url: ${intervals.base-url}
  messaging:
    nats:
      connection:
        servers:
          - "${CAPACNAN_SERVER_URI:nats://localhost:4222}"

'%dev':
  quarkus:
    rest-client:
      intervals:
        logging:
          scope: all
          body-limit: 10240
    log:
      #      level: DEBUG
      category:
        "io.quarkus.rest.client.reactive":
          level: DEBUG
