name: Build and Push Native ARM64 Container

on:
  push:
    branches: [ "main" ] # Triggers whenever you push to main

env:
  REGISTRY: ghcr.io
  # This uses your github repository name in lowercase as the image name
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm64

    # Permissions required to write images to GitHub Packages
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      # Install GraalVM/Mandrel directly onto the ARM machine host
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'mandrel'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # Sets up Docker Buildx for multi-architecture image packaging
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Native App
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew build \
            -Dquarkus.package.type=native \
            -Dquarkus.test.continuous-testing=disabled \
            -Dquarkus.native.container-build=false

      # Logs into GitHub Container Registry using the built-in GitHub token
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Convert repository name to lowercase to prevent Docker tagging issues
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and Push Container via Buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
